config/routes.rb
Info::Application.routes.draw do
  resources :theaters

  resources :shows

  resources :orgs

  resources :people

  resources :plays

  get "home/index"

  root to: "home#index"

  

end

app/models/org.rb
class Org < ActiveRecord::Base
  has_many :people
end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
  before_action :set_org, only: [:show, :edit, :update, :destroy]

  # GET /orgs
  # GET /orgs.json
  def index
    @orgs = Org.all
  end

  # GET /orgs/1
  # GET /orgs/1.json
  def show
  end

  # GET /orgs/new
  def new
    @org = Org.new
  end

  # GET /orgs/1/edit
  def edit
  end

  # POST /orgs
  # POST /orgs.json
  def create
    @org = Org.new(org_params)

    respond_to do |format|
      if @org.save
        format.html { redirect_to @org, notice: 'Org was successfully created.' }
        format.json { render action: 'show', status: :created, location: @org }
      else
        format.html { render action: 'new' }
        format.json { render json: @org.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orgs/1
  # PATCH/PUT /orgs/1.json
  def update
    respond_to do |format|
      if @org.update(org_params)
        format.html { redirect_to @org, notice: 'Org was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @org.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orgs/1
  # DELETE /orgs/1.json
  def destroy
    @org.destroy
    respond_to do |format|
      format.html { redirect_to orgs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_org
      @org = Org.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def org_params
      params.require(:org).permit(:name, :address, :url)
    end
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/views/orgs/_form.html.erb
<%= form_for(@org) do |f| %>
  <% if @org.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@org.errors.count, "error") %> prohibited this org from being saved:</h2>

      <ul>
      <% @org.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orgs/edit.html.erb
<h1>Editing org</h1>

<%= render 'form' %>

<%= link_to 'Show', @org %> |
<%= link_to 'Back', orgs_path %>

app/views/orgs/index.html.erb
<h1>Listing orgs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orgs.each do |org| %>
      <tr>
        <td><%= link_to org.name, org.url, :target=>"_blank" %></td>
        <td><%= org.address %></td>
        <td><%= link_to 'Edit', edit_org_path(org) %></td>
        <td><%= link_to 'Destroy', org, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Org', new_org_path %>

app/views/orgs/new.html.erb
<h1>New org</h1>

<%= render 'form' %>

<%= link_to 'Back', orgs_path %>

app/views/orgs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @org.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @org.address %>
</p>

<p>
  <strong>Url:</strong>
  <%= @org.url %>
</p>

<%= link_to 'Edit', edit_org_path(@org) %> |
<%= link_to 'Back', orgs_path %>