config/routes.rb
Info::Application.routes.draw do
  resources :theaters

  resources :shows

  resources :orgs

  resources :people

  resources :plays

  get "home/index"

  root to: "home#index"

  

end

app/models/play.rb
class Play < ActiveRecord::Base
  has_many :shows
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :set_play, only: [:show, :edit, :update, :destroy]

  # GET /plays
  # GET /plays.json
  def index
    @plays = Play.all
  end

  # GET /plays/1
  # GET /plays/1.json
  def show
  end

  # GET /plays/new
  def new
    @play = Play.new
  end

  # GET /plays/1/edit
  def edit
  end

  # POST /plays
  # POST /plays.json
  def create
    @play = Play.new(play_params)

    respond_to do |format|
      if @play.save
        format.html { redirect_to @play, notice: 'Play was successfully created.' }
        format.json { render action: 'show', status: :created, location: @play }
      else
        format.html { render action: 'new' }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plays/1
  # PATCH/PUT /plays/1.json
  def update
    respond_to do |format|
      if @play.update(play_params)
        format.html { redirect_to @play, notice: 'Play was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plays/1
  # DELETE /plays/1.json
  def destroy
    @play.destroy
    respond_to do |format|
      format.html { redirect_to plays_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_play
      @play = Play.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def play_params
      params.require(:play).permit(:name, :story)
    end
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/views/plays/_form.html.erb
<%= form_for(@play) do |f| %>
  <% if @play.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@play.errors.count, "error") %> prohibited this play from being saved:</h2>

      <ul>
      <% @play.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :story %><br>
    <%= f.text_field :story %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plays/edit.html.erb
<h1>Editing play</h1>

<%= render 'form' %>

<%= link_to 'Show', @play %> |
<%= link_to 'Back', plays_path %>

app/views/plays/index.html.erb
<h1>Listing plays</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @plays.each do |play| %>
      <tr>
        <td><%= link_to play.name, play.story, :target=>"_blank" %></td>
        <td><%= link_to 'Edit', edit_play_path(play) %></td>
        <td><%= link_to 'Destroy', play, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Play', new_play_path %>

app/views/plays/new.html.erb
<h1>New play</h1>

<%= render 'form' %>

<%= link_to 'Back', plays_path %>

app/views/plays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @play.name %>
</p>

<p>
  <strong>Story:</strong>
  <%= @play.story %>
</p>

<%= link_to 'Edit', edit_play_path(@play) %> |
<%= link_to 'Back', plays_path %>