config/routes.rb
Info::Application.routes.draw do
  resources :theaters

  resources :shows

  resources :orgs

  resources :people

  resources :plays

  get "home/index"

  root to: "home#index"

  

end

app/models/theater.rb
class Theater < ActiveRecord::Base
end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  before_action :set_theater, only: [:show, :edit, :update, :destroy]

  # GET /theaters
  # GET /theaters.json
  def index
    @theaters = Theater.all
  end

  # GET /theaters/1
  # GET /theaters/1.json
  def show
  end

  # GET /theaters/new
  def new
    @theater = Theater.new
  end

  # GET /theaters/1/edit
  def edit
  end

  # POST /theaters
  # POST /theaters.json
  def create
    @theater = Theater.new(theater_params)

    respond_to do |format|
      if @theater.save
        format.html { redirect_to @theater, notice: 'Theater was successfully created.' }
        format.json { render action: 'show', status: :created, location: @theater }
      else
        format.html { render action: 'new' }
        format.json { render json: @theater.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theaters/1
  # PATCH/PUT /theaters/1.json
  def update
    respond_to do |format|
      if @theater.update(theater_params)
        format.html { redirect_to @theater, notice: 'Theater was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @theater.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theaters/1
  # DELETE /theaters/1.json
  def destroy
    @theater.destroy
    respond_to do |format|
      format.html { redirect_to theaters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theater
      @theater = Theater.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theater_params
      params.require(:theater).permit(:name, :address)
    end
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/views/theaters/_form.html.erb
<%= form_for(@theater) do |f| %>
  <% if @theater.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theater.errors.count, "error") %> prohibited this theater from being saved:</h2>

      <ul>
      <% @theater.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/theaters/edit.html.erb
<h1>Editing theater</h1>

<%= render 'form' %>

<%= link_to 'Show', @theater %> |
<%= link_to 'Back', theaters_path %>

app/views/theaters/index.html.erb
<h1>Listing theaters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @theaters.each do |theater| %>
      <tr>
        <td><%= theater.name %></td>
        <td><%= theater.address %></td>
        <td><%= link_to 'Show', theater %></td>
        <td><%= link_to 'Edit', edit_theater_path(theater) %></td>
        <td><%= link_to 'Destroy', theater, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theater', new_theater_path %>

app/views/theaters/new.html.erb
<h1>New theater</h1>

<%= render 'form' %>

<%= link_to 'Back', theaters_path %>

app/views/theaters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @theater.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @theater.address %>
</p>

<%= link_to 'Edit', edit_theater_path(@theater) %> |
<%= link_to 'Back', theaters_path %>